version: '3'

services:
  host:
    build: ./host
    ports:
      - 8081:80
      - 1313:1313
      - 3000:3000
      - 5000:5000
      - 8000:8000
      - 8080:8080
      - 9000:9000
    volumes:
      - ./workspace:/home/carlos/workspace
